name: Get Default Themes
description: Downloads default themes to be packaged for RetroHub
inputs:
  tag:
    description: The tag version to download
    required: true
runs:
  using: composite
  steps:
    - name: Setup workdir
      shell: sh
      run: |
        mkdir -p -v themes_workdir

    - name: Download [default]
      shell: sh
      env:
        THEME_NAME: default.pck
      run: |
        cd themes_workdir
        curl -L https://github.com/retrohub-org/default-theme/releases/download/${{ inputs.tag }}/${{ env.THEME_NAME }} --output ${{ env.THEME_NAME }}

    - name: Download [es-theme-wrapper]
      shell: sh
      env:
        THEME_NAME: es-theme-wrapper.pck
      run: |
        cd themes_workdir
        curl -L https://github.com/retrohub-org/es-theme-wrapper/releases/download/${{ inputs.tag }}/${{ env.THEME_NAME }} --output ${{ env.THEME_NAME }}

    - name: Package themes
      shell: sh
      run: |
        cd themes_workdir
        for theme in *.pck; do
          echo "$theme" >> ../retrohub/default_themes/themes.txt
        done
        cat ../retrohub/default_themes/themes.txt
        mv *.pck ../retrohub/default_themes
        ls -la ../retrohub/default_themes
